---
abstract: 'CRUD-type plugin to manage YouTube videos'
author:
  - "Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-YouTube
provides:
  App::ZofCMS::Plugin::YouTube:
    file: lib/App/ZofCMS/Plugin/YouTube.pm
    version: 0.0105
requires:
  App::ZofCMS::Plugin::Base: 0.0102
  DBI: 1.602
  HTML::Entities: 1.35
  HTML::Template: 2.9
  LWP::UserAgent: 2.036
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0105
